/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c73e10ca2457f41f867107f22fedbd64)
declare namespace Cloudflare {
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		PAYMENT_SERVICE: Fetcher;
		R2_BUCKET: R2Bucket;
		MY_QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {
	ELEVENLABS_API_KEY?: string;
	CLOUDFLARE_ACCOUNT_ID?: string;
	AI_GATEWAY_ID?: string;
}
